---
# control
control:
  data_name: MVN
  test_mode: cvm
  ptb: 0.1-0
  num_samples: 100
# experiment
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
verbose: False
