---
# control
control:
  data_name: MVN
  model_name: mvn
  ht_mode: hst
  ptb: 0.1-0
# experiment
pin_memory: True
num_worker: 0
init_seed: 0
num_experiment: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
verbose: False
